baseURL = 'https://cake-8gr.pages.dev/'
languageCode = "ja-jp"
title = "あなたのケーキ言葉占い"
assetDir = "assets"
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
